"""Update status to unverified/pending/approved

Revision ID: c64b54e792b1
Revises: c64b54e792b0
Create Date: 2025-12-26 14:49:52.197285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64b54e792b1'
down_revision: Union[str, Sequence[str], None] = 'c64b54e792b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Changes the member status column default from 'pending' to 'unverified'
    to align with the new registration flow where users start as UNVERIFIED
    and move to PENDING after email verification.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # For SQLite: we need to recreate the table since SQLite has limited ALTER TABLE support
    # This approach is a simplified version - in production with PostgreSQL/MySQL,
    # you could use a simpler ALTER COLUMN ... SET DEFAULT command

    # Get the bind to determine database dialect
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        # SQLite approach: recreate table
        op.execute("""
            CREATE TABLE member_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email VARCHAR(255) NOT NULL UNIQUE,
                name VARCHAR(100) NOT NULL,
                generation INTEGER NOT NULL,
                rank VARCHAR(50) NOT NULL,
                description TEXT,
                image_url VARCHAR(500),
                status VARCHAR(50) NOT NULL DEFAULT 'unverified',
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
        """)

        op.execute("""
            INSERT INTO member_new (id, email, name, generation, rank, description, image_url, status, created_at, updated_at)
            SELECT id, email, name, generation, rank, description, image_url,
                   COALESCE(status, 'unverified') as status,
                   created_at, updated_at
            FROM member;
        """)

        op.execute("DROP TABLE member;")
        op.execute("ALTER TABLE member_new RENAME TO member;")

        # Recreate indexes
        op.execute("CREATE INDEX ix_member_email ON member (email);")
    else:
        # PostgreSQL/MySQL approach: simpler ALTER COLUMN
        op.execute("""
            ALTER TABLE member
            ALTER COLUMN status
            SET DEFAULT 'unverified';
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Reverts the member status column default back to 'pending'.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        # SQLite approach: recreate table
        op.execute("""
            CREATE TABLE member_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email VARCHAR(255) NOT NULL UNIQUE,
                name VARCHAR(100) NOT NULL,
                generation INTEGER NOT NULL,
                rank VARCHAR(50) NOT NULL,
                description TEXT,
                image_url VARCHAR(500),
                status VARCHAR(50) NOT NULL DEFAULT 'pending',
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
        """)

        op.execute("""
            INSERT INTO member_new (id, email, name, generation, rank, description, image_url, status, created_at, updated_at)
            SELECT id, email, name, generation, rank, description, image_url, status, created_at, updated_at
            FROM member;
        """)

        op.execute("DROP TABLE member;")
        op.execute("ALTER TABLE member_new RENAME TO member;")

        # Recreate indexes
        op.execute("CREATE INDEX ix_member_email ON member (email);")
    else:
        # PostgreSQL/MySQL approach: simpler ALTER COLUMN
        op.execute("""
            ALTER TABLE member
            ALTER COLUMN status
            SET DEFAULT 'pending';
        """)

    # ### end Alembic commands ###
